import os
import google.generativeai as genai
import re

# Configure the Gemini API key
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
genai.configure(api_key=GEMINI_API_KEY)

# Set up the model
generation_config = {
  "temperature": 0.3,
  "top_p": 1,
  "top_k": 1,
  "max_output_tokens": 8192,
}

model = genai.GenerativeModel(model_name="gemini-1.5-flash",
                              generation_config=generation_config)

async def generate_code_with_gemini(brief: str, task: str) -> dict:
    prompt = f"""Create a complete web application based on the following brief.

Task: {task}
Brief: {brief}

You must follow these requirements strictly:
1.  The entire application must be contained within a single `index.html` file.
2.  All CSS and JavaScript must be embedded directly within the HTML file.
3.  The design should be modern, clean, and responsive.
4.  The application must be fully functional and meet all requirements described in the brief.
5.  Do not use any external libraries, frameworks, or dependencies unless explicitly asked for in the brief.
6.  Your final output must be ONLY the raw HTML code for the `index.html` file, enclosed in a single markdown code block. Do not include any other text, explanations, or formatting outside of the code block.

Example Output:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My App</title>
    <style>
        /* CSS goes here */
    </style>
</head>
<body>
    <!-- HTML content goes here -->
    <script>
        // JavaScript goes here
    </script>
</body>
</html>
```
"""

    convo = model.start_chat()
    await convo.send_message_async(prompt)
    response = convo.last

    html_code = response.text.strip()

    # Clean up markdown code block fences
    match = re.search(r"```html\n(.*?)\n```", html_code, re.DOTALL)
    if match:
        html_code = match.group(1).strip()
    elif html_code.startswith("```") and html_code.endswith("```"):
        html_code = html_code[3:-3].strip()

    return {
        "index.html": html_code,
        "README.md": f"# {task}\n\n{brief}\n\nThis project was generated by Google Gemini. Open index.html to use the application."
    }